# Makefile
# Generated by Makefile Generater at Tue Mar  6 13:37:12 2012

TARGET = main
CC = g++
OBJS = modelerdraw.o util.o modelerui.o camera.o modelerview.o bitmap.o modelerapp.o sample.o
SRCS = modelerdraw.cpp util.cpp modelerui.cxx camera.cpp modelerview.cpp bitmap.cpp modelerapp.cpp sample.cpp
CXXFLAGS = $(shell fltk-config --use-gl --use-images --cxxflags ) -I. 
LDFLAGS = $(shell fltk-config --use-gl --use-images --ldflags ) 
LDSTATIC = $(shell fltk-config --use-gl --use-images --ldstaticflags ) 
DEBUG = -g
LINK = $(CC)

# LINK = $(shell fltk-config --use-gl --compile)

.SUFFIXES: .o .cpp .cxx
%.o: %.cpp
	$(CC) $(DEBUG) $(CXXFLAGS) -c $<

%.o: %.cxx
	$(CC) $(DEBUG) $(CXXFLAGS) -c $<

all: $(TARGET)
	$(LINK) -o $(TARGET) $(OBJS) $(LDSTATIC)

$(TARGET): $(OBJS)
modelerdraw.cpp : modelerdraw.h util.h modelerglobals.h
modelerapp.cpp : modelerapp.h modelerview.h modelerui.h util.h bitmap.h modelerdraw.h modelerglobals.h
modelerview.cpp : modelerview.h camera.h util.h vec.h mat.h
modelerui.cxx : modelerui.h modelerapp.h util.h camera.h modelerview.h bitmap.h modelerdraw.h vec.h mat.h modelerglobals.h
util.cpp : util.h
bitmap.cpp : bitmap.h
camera.cpp : camera.h vec.h mat.h
sample.cpp : modelerview.h modelerapp.h modelerdraw.h modelerglobals.h

clean:
	@rm $(OBJS) -vf
	@rm $(TARGET) -vf
	@echo "Clean successfully"

# end of Makefile
